services:
  backend:
    build: ./backend
    container_name: app-backend
    depends_on:
      - postgres
      - vault
      - wrapper-java
    environment:
      - NODE_ENV=development
      - PORT=3000
      - WRAPPER_URL=http://wrapper-java:8080
      - VAULT_ADDR=http://vault:8200
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=app
      - DB_PASSWORD=secret
      - DB_NAME=appdb
    ports:
      - "3000:3000" # для дебага, потом можно убрать
    networks:
      - app-net

# ниже то, что было для заглушки сервиса - пока оставлю
  # wrapper-java:
  #   image: eclipse-temurin:21-jre-alpine
  #   container_name: app-wrapper-java
  #   depends_on:
  #     - vault
  #     - postgres
  #   environment:
  #     - SERVER_PORT=8080
  #   command: ["sh", "-c", "echo 'wrapper-java placeholder started'; sleep 3600"]
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - app-net

  wrapper-java:
    build:
      context: ./wrapper-java
      dockerfile: Dockerfile
    container_name: app-wrapper-java
    environment:
      - VAULT_ADDR=http://app-vault:8200
      - VAULT_TOKEN=root
    depends_on:
      - vault
    networks:
      - app-net


  postgres:
    image: postgres:16
    container_name: app-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-net
    ports:
      - "5432:5432"

  vault:
    image: hashicorp/vault:1.16
    container_name: app-vault
    restart: unless-stopped
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    networks:
      - app-net
    command: ["server", "-dev"]

  nginx:
    image: nginx:1.27
    container_name: app-nginx
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - app-net

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: app-keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command:
      - start-dev
      - --http-port=8080
      - --hostname=localhost
    ports:
      - "8081:8080"
    networks:
      - app-net


networks:
  app-net:

volumes:
  pgdata:




# version: "3.9"

# services:
#   backend:
#     build: ./backend
#     container_name: app-backend
#     depends_on:
#       - postgres
#       - vault
#       - wrapper-java
#     environment:
#       - NODE_ENV=development
#       - PORT=3000
#       - WRAPPER_URL=http://wrapper-java:8080
#       - VAULT_ADDR=http://vault:8200
#       - DB_HOST=postgres
#       - DB_PORT=5432
#       - DB_USER=app
#       - DB_PASSWORD=secret
#       - DB_NAME=appdb
#     ports:
#       - "3000:3000" # временно, чтобы удобно было дебажить
#     networks:
#       - app-net

#   wrapper-java:
#     build: ./wrapper-java
#     container_name: app-wrapper-java
#     depends_on:
#       - vault
#       - postgres
#     environment:
#       - SERVER_PORT=8080
#       - VAULT_ADDR=http://vault:8200
#       - DB_URL=jdbc:postgresql://postgres:5432/appdb
#       - DB_USER=app
#       - DB_PASSWORD=secret
#     ports:
#       - "8080:8080" # временно, для дебага
#     networks:
#       - app-net

#   postgres:
#     image: postgres:16
#     container_name: app-postgres
#     restart: unless-stopped
#     environment:
#       - POSTGRES_DB=appdb
#       - POSTGRES_USER=app
#       - POSTGRES_PASSWORD=secret
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#       # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # позже
#     networks:
#       - app-net
#     ports:
#       - "5432:5432" # для локальной работы

#   vault:
#     image: hashicorp/vault:1.16
#     container_name: app-vault
#     restart: unless-stopped
#     environment:
#       - VAULT_DEV_ROOT_TOKEN_ID=root
#       - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
#     cap_add:
#       - IPC_LOCK
#     ports:
#       - "8200:8200"
#     networks:
#       - app-net
#     command: ["server", "-dev"]

#   nginx:
#     image: nginx:1.27
#     container_name: app-nginx
#     depends_on:
#       - backend
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#     ports:
#       - "80:80"
#     networks:
#       - app-net

# networks:
#   app-net:

# volumes:
#   pgdata:
